CI/azure-pipelines-build.yml, CI/azure-pipelines-windows.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/Compare.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs
- Add reading image from Stream (Not MemoryStream)
- Add reading image form Uri
- Remove Unit test x86 from NET50, and NETCOREAPP3.1
- Add Unit test x86 for NET60
=> Iron 569 iron barcode create qr code with logo does not add logos to centre of qr code add support for swiss qr

CI/azure-pipelines-build.yml, NuGet/IronSoftware.Drawing.nuspec
=> update github connection

CI/azure-pipelines-build.yml, CI/azure-pipelines-mac.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/ColorFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/FontFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/XUnitAttributes/IgnoreOnMacFactAttribute.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/XUnitAttributes/IgnoreOnUnixFactAttribute.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/CropRectangle.cs
Add Redact function to cover the specific region with specific color.
- Add Top, Left, Right, and Bottom to CropRectangle
- Add Contains(x, y) to determines if the specified point is contained within the rectangular region defined by CropRectangle
=> Iron 863 iron barcode expect multiple barcodes not working with one dimensional barcodes

NuGet/IronSoftware.Drawing.nuspec, NuGet/README.txt
- Add .NET 8 support
- Edit release notes
=> NuGet Package Explorer Review Changes

NuGet/IronSoftware.Drawing.nuspec
- Updated releasenotes
Run Unit tests locally.
=> Prepare for new version release

CI/azure-pipelines-build.yml, CI/stage_templates/run_tests_on_pool.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/Context/TestingTraits.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/IronSoftware.Drawing.Common.Tests.csproj, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/TargetFramework.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/TestsBase.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/ColorFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/Compare.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/FontFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/XUnitAttributes/IgnoreOnMacFactAttribute.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/XUnitAttributes/IgnoreOnUnixFactAttribute.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Color.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/CropRectangle.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Font.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, IronSoftware.Drawing/IronSoftware.Drawing.Common/KnownColors.cs, IronSoftware.Drawing/IronSoftware.Drawing.sln, NuGet/IronSoftware.Drawing.nuspec
This PR updates the nuget packages to their latest supported versions, adds explicit dependency on System.Memory 4.5.5
to fix the warnings that arise because some dependencies still use earlier version of it. This also fixes private/internal variables' and class members', and method parameters' naming to be more uniform and consistent. WARNING: this makes one breaking change if a developer is using method parameter names in their code - there will be design-time errors after this update.
It also changes release pipeline to be flexible to not need a release branch. Adds ability to control of unit test should or should not run.
Fixes all compiler warnings apart from an obsolete methods, and all compiler suggestions.
Please select the relevant option by placing an 'x' inside the brackets, …
=> Fixing the System.Memory conflict warning in Iron Software products.

NuGet/IronSoftware.Drawing.nuspec
Update release notes for November release
=> November release notes

IronSoftware.Drawing/IronSoftware.Drawing.Common/Legacy/CropRectangle.cs, NuGet/IronSoftware.Drawing.nuspec, NuGet/README.md, README.md
=> Release 2023.12 into Master

CI/azure-pipelines-build.yml, CI/job_templates/deploy_drawing_libraries.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common/Point.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Rectangle.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Size.cs, NuGet/IronSoftware.Drawing.nuspec, NuGet/README.md, README.md
Merge into `develop` after release done.
=> [develop] Hotfix 2024.3 to address known vulnerabilities

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/IronSoftware.Drawing.Common.Tests.csproj, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/TargetFramework.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
Update SixLabors.ImageSharp & SixLabors.ImageSharp.Drawing to address known vulnerabilities.
Release process as usual. This need to be merge after release May version.
=> [develop] Release 2024.5

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/IronSoftware.Drawing.Common.Tests.csproj, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/TargetFramework.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
Update SixLabors.ImageSharp & SixLabors.ImageSharp.Drawing to address known vulnerabilities.
Release process as usual. This need to be merge after release May version.
=> [master] Release 2024.5

NuGet/IronSoftware.Drawing.nuspec
=> Release 2024.6 [develop]

NuGet/IronSoftware.Drawing.nuspec
IronDrawing Release for v2024.7.2
=> Releases/2024.7 [develop]

IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
This pull request updates the version of the SixLabors.ImageSharp.Drawing package to 2.1.4. This update addresses known vulnerabilities and ensures compatibility with the latest dependencies.
And this branch for preparing to release the hotfix version.
=> [master] Hotfix/2024.8.1

IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, IronSoftware.Drawing/nuget.config, NuGet/IronSoftware.Drawing.nuspec
This change allows images to be shared across projects without requiring a hard reference to the IronSoftware.System.Drawing package
- Add dependency to IronSoftware.Common public nuget package
- `AnyBitmap` implements `IAnyImage`
=> Implement Image Interface

NuGet/IronSoftware.Drawing.nuspec
**IronDrawing Release for 2024.9.x version**
Below is the change made in this PR
- Release note update.
*The internal dependencies has been updated in the develop branch by JD already
=> [develop] IronDrawing Release/2024.9 [Do not merge until the product is released]

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/RectangleFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Extensions/MeasurementUnitExtensions.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Rectangle.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/RectangleF.cs
Make sure the title of the PR is descriptive and summarizes the changes made.
Model `IronSoftware.Drawing.Rectangle` contains a Property named `MeasurementUnit`. This MeasurementUnit enum contains only 2 values. (Pixel and Millimeters). And the default value is considered as Pixel. But, in PDF we use another type of Measurement unit which is called Point (1 Point = 1 Inch / 72). So we have to add one more enum value Point to the MeasurementUnit enum.
Fixes #(PDF-1489)
Fixes #(PDF-1689)
Describe the tests you ran to verify your changes. Provide instructions so others can reproduce the tests. Also, list any relevant details for your …
=> Add Point to MeasurementUnit Enum

IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
Make sure the title of the PR is descriptive and summarizes the changes made.
Provide a brief description of the changes made in this PR. Explain what the PR does, what issue it resolves, or what feature it adds.
Describe the tests you ran to verify your changes. Provide instructions so others can reproduce the tests. Also, list any relevant details for your test configuration.
=> update Abstractions to 2025.2.6

CI/azure-pipelines-build.yml, CI/job_templates/deploy_drawing_libraries.yml, CI/step_templates/sign_drawing_libraries_dll.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec, NuGet/README.md, NuGet/README.txt, README.md
- Add .NET 9.0 support in the nuspec and readme file
- Add new signing by Meee
=> [develop] Releases/2025.7 Changes

IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
- Update SixLabors.ImageSharp to latest version to resolve vulnerability issue reported in the dependencies
=> [develop] Release/2025.8 Preparation

IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
- Update SixLabors.ImageSharp to latest version to resolve vulnerability issue reported in the dependencies
=> [master] Releases/2025.8 Preparation
