NuGet/IronSoftware.Drawing.nuspec
adds nuget dependency to System.Memory v4.5.5 for net462
this fixes the issue when I do this locally, should hopefully work
=> adds nuget dependency to System.Memory v4.5.5 for net462

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/TargetFramework.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/ColorFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Color.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/CropRectangle.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/KnownColor.cs, NuGet/IronSoftware.Drawing.nuspec
* AnyBitmap
- GetPixel(x, y) which is a new accessor method to get the Color of a pixel in an AnyBitmap
- Adds new constructor to AnyBitmap which creates a new AnyBitmap from an existing AnyBitmap, scaled to the a custom width and height
- Fixes a bug when saving an image without specifying ImageFormat
* Color
- [Hotfix] Fixes a bug when comparing Color with null
=> Iron 867 iron barcode upgrade new iron drawing version

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/IronSoftware.Drawing.Common.Tests.csproj, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
- Including `SixLabors.ImageSharp.Drawing` and `SixLabors.Fonts` into lib folder
- Update copyright
=> Iron 867 fixing framework

IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Color.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/CropRectangle.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Font.cs
- Adds `href` links to website documentation code examples.
=> Add IntelliSense linking to Website Code Examples

README.md
- Uses compatibility tables over bullets for increased readability.
=> Update readme support to tables

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/ColorFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Color.cs
Some value will return 1 digit instead of 2.
Eg.
```
Color color = Color.FromArgb(0, 64, 244, 208);
color.ToString(); // Should be #0040F4D0
```
=> Fixes Color.ToString() return incorrect

CI/azure-pipelines-build.yml
- Install .NET 3.x
- Remove --blame-crash, --blame-hang for netcoreapp3.1
=> Fixes deployment pipeline failed

IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs
add destructor for AnyBitmap so Dispose() isn't always necessary
=> add destructor for AnyBitmap so Dispose() isn't always necessary

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/ColorFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Color.cs, NuGet/IronSoftware.Drawing.nuspec
This translates the specified Color structure to an HTML string color representation.
=> Added a new function call to the Color class: ToHtml()

IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, NuGet/IronSoftware.Drawing.nuspec
- Updated `MissingMethodException` or `TypeInitializationException` message to "Due to conflicts between SixLabors.ImageSharp v2 and v3, to use SixLabors.ImageSharp v3 with Iron Software products please install IronSoftware.System.Drawing v.2023.4.1-prerelease NuGet package which supports SixLabors.ImageSharp v3."
- Updated releasenotes
Run Unit tests locally.
=> Prepare for old SixLabors version release

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/Compare.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, NuGet/IronSoftware.Drawing.nuspec
In this PR, two new methods were implemented:
`LoadAnyBitmapFromRGBBuffer`: This method creates an AnyBitmap object from a provided buffer of RGB pixel data. It takes in a byte array, along with width and height parameters, and returns an AnyBitmap object.
```
byte[] buffer = YOUR_RGB_BUFFER;
using AnyBitmap result = AnyBitmap.LoadAnyBitmapFromRGBBuffer(buffer, width, height);
```
`GetRGBBuffer`: This method retrieves the RGB buffer from an AnyBitmap object. It returns an array of bytes representing the RGB buffer of the image.
```
using var bitmap = new AnyBitmap(YOUR_IMAGE_PATH);
byte[] buffer = bitmap.GetRGBBuffer();
```
These methods provide more flexibility when working with images and RGB data, simplifying the process of creating AnyBitmap objects from RGB buffers and retrieving RGB …
=> Feature: Added methods to load AnyBitmap from RGB buffer and retrieve RGB buffer from image

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs
Fixes #1215
Describe the tests you ran to verify your changes. Provide instructions so others can reproduce the tests. Also, list any relevant details for your test configuration.
=> IRON-1215 SetPixel Implementation

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/ColorFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Color.cs, NuGet/IronSoftware.Drawing.nuspec
- Add AnyBitmap constructor to creating blank image
```csharp
var bitmap = new AnyBitmap(8, 8);
bitmap.SaveAs("blank_bitmap.jpg");
```
- Add GetBrightness to calculates the brightness of a color.
```csharp
Color color = Color.Black;
double brightness = color.GetBrightness();
```
Add unit tests to test each function.
=> Implement color get brightness & create blank image

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/FontFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Extensions/Enumeration.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Font.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/FontTypes.cs, NuGet/IronSoftware.Drawing.nuspec, NuGet/README.md
1. Move IronPdf.Font.FontTypes into IronDrawing
2. Implement casting between FontTypes and Font
Casting FontTypes to Font
```csharp
IronSoftware.Drawing.Font font = IronPdf.Font.FontTypes.TimesNewRomanBoldItalic;
```
Casting FontTypes from Font
```charp
var font = new IronSoftware.Drawing.Font("Courier New", FontStyle.Bold);
IronPdf.Font.FontTypes fontTypes = font;
```
Fixes [IRON-1284](https://ironsoftware.atlassian.net/browse/IRON-1284)
Add 3 unit tests
1. Casting FontTypes to Font
2. Casting Font to FontTypes
3. Casting Font to FontTypes should throw exception if font not supported in FontTypes
Please run through the checklist as much as possible and mark the items completed by placing an 'x' …
=> Implement casting between IronPdf.Font.FontTypes and Font

IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs
From memory leak which @djrecipe raise on Friday.
The source object can't `Dispose()` when finished casting because it may lead to another issue.
In this PR add the XML comment to `AnyBitmap` and `implicit casting` to describe the source image object should be dispose by themself.
=> Updates AnyBitmap implicit casting XML Comments

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/IronSoftware.Drawing.Common.Tests.csproj, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
- Fixed issue can't create blank image with Background color.
- Upgrade ImageSharp.Image (2.1.5 netstandard2.0 and netstandard2.1, 3.0.1 net6.0+) and ImageSharp.Drawing (1.0.0) to latest version.
- Now NuGet package including ImageSharp.Drawing (1.0.0) as dependency.
Create unit tests and also test the final package.
=> Hotfix September RC

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/IronSoftware.Drawing.Common.Tests.csproj, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
When build Xamarin application it will look into all dependency inside the DLL. This PR intend to fix that problem by adding all missing library into netstandard2.1 dependency.
Now NuGet package on Monandroid10.0 will include:
1. SkiaSharp
2. SkiaSharp.Svg
3. Microsoft.Maui.Graphics
Testing by @michael-ironsoftware on Xamarin application.
=> Fix mobile compatiblity

CI/azure-pipelines-build.yml, CI/job_templates/build_drawing_libraries.yml
The revision version of assembly version should be between minor and patch instead of last digit.
Ex. NuGet Version is 2023.10.1, Assembly Version should be 2023.10.0.1
Run pipeline and check assembly version. Please check [here](https://dev.azure.com/ironcoders/IronCommon/_artifacts/feed/IronCommon/NuGet/IronSoftware.System.Drawing/overview/2023.9.15-prerelease).
=> Fixes Assembly version

CI/azure-pipelines-build.yml, CI/job_templates/build_drawing_libraries.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
Using SixLabors.ImageSharp.Drawing v2.0.0 to net6.0 framework. SixLabors.Fonts will be included too because its dependency of SixLabors.ImageSharp.Drawing.
This to prevent issue when upgrading SixLabors.ImageSharp.Drawing or SixLabors.Fonts on NET6.0 or later.
Now IronDrawing dependencies goes crazy.
Fixes [QR-8](https://ironsoftware.atlassian.net/browse/DW-8)
Create RC and tested on BarCode.
=> DW-8 SixLabors ImageSharp drawing version

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/IronSoftware.Drawing.Common.Tests.csproj, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/FontFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/XUnitAttributes/IgnoreOnUnixFactAttribute.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
Update SkiaSharp to v2.88.6 which fixed vulnerable to CVE-2023-4863
=> Fixed vulnerable to CVE-2023-4863

IronSoftware.Drawing/IronSoftware.Drawing.Common/Legacy/CropRectangle.cs, NuGet/IronSoftware.Drawing.nuspec, NuGet/README.md, README.md
=> Release 2023.12 into Develop

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/RectangleFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Rectangle.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/RectangleF.cs
Make sure the title of the PR is descriptive and summarizes the changes made.
Provide a brief description of the changes made in this PR. Explain what the PR does, what issue it resolves, or what feature it adds.
Describe the tests you ran to verify your changes. Provide instructions so others can reproduce the tests. Also, list any relevant details for your test configuration.
=> Adds RectangleF Class

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/SizeFFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/SizeFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Rectangle.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/RectangleF.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Size.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/SizeF.cs, NuGet/README.md, README.md
Add Size & SizeF structs and modify Rectangle & RectangleF to have constructors that make use of these structs.
Adds the Size & SizeF structs (somewhat simplified) from SixLabors.
Doesn't fix any particular issue, but will be useful in IronPrint to specify sizes for printing.
Added unit tests from SixLabors.
=> Add Size & SizeF structs

CI/azure-pipelines-linux.yml, CI/azure-pipelines-mac.yml, CI/azure-pipelines-windows.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs
Rename `backgrounColor` to `backgroundColor`
Fixes #91
Tested with CI pipeline
=> Fix typo in AnyBitmap constructor parameter

IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Color.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Font.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Legacy/CropRectangle.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Point.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/PointF.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/Rectangle.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/RectangleF.cs
Fix spelling across the board for 'be cast' -> 'be casted'
N/A
=> Fix spelling across the board for 'be cast' -> 'be casted'

IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, IronSoftware.Drawing/nuget.config, NuGet/IronSoftware.Drawing.nuspec
Upgrade SixLabors.ImageSharp to v3.1.3 that vulnerable free for NET6.0 or greater.
Upgrade SixLabors.ImageSharp to v2.1.7 that vulnerable free for netstandard2.0.
=> Update SixLabors version

CI/job_templates/test_drawing_libraries.yml, CI/stage_templates/run_tests_on_pool.yml, IronSoftware.Drawing/.gitattributes, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/Data/RenderedFromChrome.bmp, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/Compare.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs
The root cause of the issue lies in the `ExportBytes()` function when attempting to return a large byte array containing a giant image (4958x7016 pixels). This high resolution consumes significant memory, leading to an `OutOfMemoryException`.
Fixing only `SaveAs()` function by change to use `FileStream` instead of `byte[]`.
Doesn't have a good solution for `ExportBytes()` because we export a byte array out. To solve this issue on `x86` please change to use `ExportStream()` instead.
Fixes #[DW-23](https://ironsoftware.atlassian.net/browse/DW-23)
Test locally using `x86` and add `x86` tests on DevOps (.NET472, .NET60, and .NET70)
Please run through the checklist as much as possible and mark the items …
=> DW-23: Fixing System.OutOfMemoryException in x86

CI/job_templates/build_drawing_libraries.yml, CI/stage_templates/run_tests_on_pool.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/IronSoftware.Drawing.Common.Tests.csproj, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj
- Remove netstandard2.1 build (it wasn't being included in the NuGet package, anyway)
- Only test net462/net80 (part of a broader effort to combine tests)
=> Cleanup .NET Framework Targets

IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
Upgrade SixLabour.ImageSharp to the version 2.1.9 for .netstandard 2.0 dependencies from this report: https://github.com/advisories/GHSA-63p8-c4ww-9cg7
Fixes #[DW-27](https://ironsoftware.atlassian.net/browse/DW-27)
-
-
[DW-27]: https://ironsoftware.atlassian.net/browse/DW-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DW-27] Update SixLabour.ImageSharp due to vulnerability report

IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs
Fix Out of memory exception when call GetPixel
- Stop using CloneAs in GetPixelColor (its create a whole new image in memory)
Fixes 
[DW-29](https://ironsoftware.atlassian.net/browse/DW-29)
Added unit tests
[DW-29]: https://ironsoftware.atlassian.net/browse/DW-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DW-29] stop using CloneAs in GetPixelColor

IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs
slightly improve speed of ExtractAlphaData and PrepareByteArray
- use array and index to increase speed of ExtractAlphaData
- use BlockCopy to increase speed PrepareByteArray
Fixes 
[DW-30](https://ironsoftware.atlassian.net/browse/DW-30)
all test passes,
- [] My changes generate no new warnings
[DW-30]: https://ironsoftware.atlassian.net/browse/DW-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Dw 30 optimize extract alpha data and prepare byte array

IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
- Updates IronSoftware.Abstractions to v2025.2.6
- Remove MonoAndroid Target Framework
- Update release notes
- Update copyright year to 2025
=> IronDrawing Release Preparation [2025.3]

CI/job_templates/test_drawing_libraries.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
**IronDrawing Release of 2025.5.x**
_Changes included_
- Internal update of test build script
- Disable warning messages from BitMiracle.LibTiff.NET
=> [Develop] Releases/2025.5

CI/job_templates/test_drawing_libraries.yml, IronSoftware.Drawing/IronSoftware.Drawing.Common.Tests/UnitTests/AnyBitmapFunctionality.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
Make sure the title of the PR is descriptive and summarizes the changes made.
Add an option to determine whether keeping original pixel format or load as `<Rgba32>` while loading image.
This PR aims eliminate the redundancy in IronOcr code base while converting `AnyBitmap` to `Leptonica.Pix`. Tesseract uses `Leptonica.Pix` as an input which require to convert from 32-bit image.
[DW-33](https://ironsoftware.atlassian.net/browse/DW-33)
[DW-32](https://ironsoftware.atlassian.net/browse/DW-32)
Add a new unit test and set `preserveOriginalFormat` to both true and false. Then verify the `AnyBitmap.BitsPerPixel`.
Please run through the checklist as much as possible and mark the items …
=> DW-33 Add preserveOriginalFormat bool while loading image

IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs, IronSoftware.Drawing/IronSoftware.Drawing.Common/IronSoftware.Drawing.Common.csproj, NuGet/IronSoftware.Drawing.nuspec
- Update `SixLabors.ImageSharp` and `SixLabors.ImageSharp.Drawing` version to address potential vulnerability issue.
- Update release notes
=> [develop] DW Releases/2025.6
